# Your workflow name
name: Deploy to Heroku

#  Run workflow on every push to main branch
on:
  push:
    branches: [main]

# Your workflow jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #check-out your repository
      - name: checkout
        uses: actions/checkout@v2
      #Important part
        name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@1.3.3 # Github action name (leave as it is)
        with:
          #Provide variables for your heroku app
          email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKUA_APP_NAME}}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache--"
          process_type : web


